//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDon
    {
        public int maCTHoaDon { get; set; }
        public int maHoaDon { get; set; }
        public int maXe { get; set; }
        public int tongTien { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
