//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CTHoaDon
    {


        [Display(Name = "Mã chi tiết hóa đơn")]
        public int maCTHoaDon { get; set; }


        [Display(Name = "Mã hóa đơn")]
        [Required(ErrorMessage = "Can not empty")]
        public int maHoaDon { get; set; }


        [Display(Name = "Mã xe")]
        [Required(ErrorMessage = "Can not empty")]
        public int maXe { get; set; }


        [Display(Name = "Tổng tiền")]
        [Required(ErrorMessage = "Can not empty")]
        public int tongTien { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
