//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuPhat
    {
        public int maCTPhieuPhat { get; set; }
        public int maPhieuPhat { get; set; }
        public int maXe { get; set; }
        public int maLoaiPhat { get; set; }
    
        public virtual LoaiPhat LoaiPhat { get; set; }
        public virtual PhieuPhat PhieuPhat { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
