//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int maHopDong { get; set; }
        public int maNguoiDung { get; set; }
        public string hotenNguoiDatXe { get; set; }
        public string email { get; set; }
        public int SDT { get; set; }
        public string ghiChu { get; set; }
        public int maXe { get; set; }
        public int soNgayThue { get; set; }
        public System.DateTime ngayLapHopDong { get; set; }
        public System.DateTime ngayThue { get; set; }
        public System.DateTime ngayTra { get; set; }
        public string diaChiNhanXe { get; set; }
        public int TongTien { get; set; }
        public bool daThanhToan { get; set; }
        public bool daDuyet { get; set; }
        public bool yeuCauHuyDon { get; set; }
        public int maTinhTrangHopDong { get; set; }
        public int maPhuongThucThanhToan { get; set; }
        [NotMapped]
        public int donGia { get; set; }
        [NotMapped]
        public string tenXe { get; set; }
        [NotMapped]
        public string tenLoaiThanhToan { get; set; }
        [NotMapped]
        public double TongDoanhThu { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhuongThucThanhToan PhuongThucThanhToan { get; set; }
        public virtual TinhTrangHopDong TinhTrangHopDong { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
