//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.CTHopDongs = new HashSet<CTHopDong>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int maHopDong { get; set; }
        public int maKhach { get; set; }
        public System.DateTime ngayLapHopDong { get; set; }
        public System.DateTime ngayThue { get; set; }
        public System.DateTime ngayTra { get; set; }
        public string diaChiNhanXe { get; set; }
        public string diaChiTraXe { get; set; }
        public int tienCoc { get; set; }
        public int maTinhTrangHopDong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHopDong> CTHopDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual TinhTrangHopDong TinhTrangHopDong { get; set; }
    }
}
