//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.CTHopDongs = new HashSet<CTHopDong>();
            this.HoaDons = new HashSet<HoaDon>();
            this.SoXes = new HashSet<SoXe>();
        }



        [Display(Name = "Mã hợp đồng")]
        public int maHopDong { get; set; }


        [Display(Name = "Mã khách")]
        [Required(ErrorMessage = "Can not empty")]
        public int maKhach { get; set; }


        [Display(Name = "Ngày lập hợp đồng")]
        [Required(ErrorMessage = "Can not empty")]
        public System.DateTime ngayLapHopDong { get; set; }


        [Display(Name = "Ngày thuê")]
        [Required(ErrorMessage = "Can not empty")]
        public System.DateTime ngayThue { get; set; }


        [Display(Name = "Ngày trả")]
        [Required(ErrorMessage = "Can not empty")]
        public System.DateTime ngayTra { get; set; }


        [Display(Name = "Địa chỉ nhận xe")]
        [Required(ErrorMessage = "Can not empty")]
        public string diaChiNhanXe { get; set; }


        [Display(Name = "Địa chỉ trả xe")]
        [Required(ErrorMessage = "Can not empty")]
        public string diaChiTraXe { get; set; }


        [Display(Name = "Tiền cọc")]
        [Required(ErrorMessage = "Can not empty")]
        public int tienCoc { get; set; }


        [Display(Name = "Mã tình trạng hợp đồng")]
        [Required(ErrorMessage = "Can not empty")]
        public int maTinhTrangHopDong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHopDong> CTHopDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual TinhTrangHopDong TinhTrangHopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoXe> SoXes { get; set; }
    }
}
