//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.HoaDons1 = new HashSet<HoaDon>();
            this.PhieuPhats = new HashSet<PhieuPhat>();
            this.SoXes = new HashSet<SoXe>();
        }



        [Display(Name = "Mã người dùng")]
        [Required(ErrorMessage = "Can not empty")]
        public int maNguoiDung { get; set; }


        [Display(Name = "Tên")]
        [Required(ErrorMessage = "Can not empty")]
        public string ten { get; set; }


        [Display(Name = "SĐt")]
        [Required(ErrorMessage = "Can not empty")]
        public string SDT { get; set; }


        [Display(Name = "Địa chỉ")]
        public string diaChi { get; set; }


        [Display(Name = "Hộ khẩu")]
        public string hoKhau { get; set; }


        [Display(Name = "Số tài khoản ngân hàng")]
        [Required(ErrorMessage = "Can not empty")]
        public string soTKNganHang { get; set; }


        [Display(Name = "Mã ngân hàng")]
        [Required(ErrorMessage = "Can not empty")]
        public int maNganHang { get; set; }


        [Display(Name = "CMND")]
        [Required(ErrorMessage = "Can not empty")]
        public string CMND { get; set; }


        [Display(Name = "Tên tài khoản")]
        [Required(ErrorMessage = "Can not empty")]
        public string username { get; set; }


        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Can not empty")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [NotMapped]
        [Compare("password")]
        [Display(Name = "Nhập lại mật khẩu")]
        public string ConfirmPass { get; set; }


        [Display(Name = "Mã quyền")]
        public int maQuyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons1 { get; set; }
        public virtual NganHang NganHang { get; set; }
        public virtual Quyen Quyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuPhat> PhieuPhats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoXe> SoXes { get; set; }
    }
}
