//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuPhat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuPhat()
        {
            this.CTPhieuPhats = new HashSet<CTPhieuPhat>();
        }



        [Display(Name = "Mã phiếu phạt")]
        public int maPhieuPhat { get; set; }


        [Display(Name = "Mã người dùng")]
        [Required(ErrorMessage = "Can not empty")]
        public int maNguoiDung { get; set; }


        [Display(Name = "Ngày lập")]
        [Required(ErrorMessage = "Can not empty")]
        public System.DateTime ngayLap { get; set; }


        [Display(Name = "Tổng tiền")]
        public int tongTien { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuPhat> CTPhieuPhats { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}