//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoXe
    {
        public int maHopDong { get; set; }
        public int maXe { get; set; }
        public int maNguoiDung { get; set; }
        public System.DateTime ngayNhan { get; set; }
        public System.DateTime ngayTra { get; set; }
        public System.DateTime ngayDatXe { get; set; }
        public System.DateTime ngayHenLay { get; set; }
        public int tienThue { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
