//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SoXe
    {

        [Display(Name = "Mã sổ xe")]
        public int maSoXe { get; set; }

        [Display(Name = "Mã hợp đồng")]
        [Required(ErrorMessage = "Can not empty")]
        public int maHopDong { get; set; }

        [Display(Name = "Mã xe")]
        [Required(ErrorMessage = "Can not empty")]
        public int maXe { get; set; }

        [Display(Name = "Mã người dùng")]
        [Required(ErrorMessage = "Can not empty")]
        public int maNguoiDung { get; set; }

        [Display(Name = "Ngày nhận")]
        [Required(ErrorMessage = "Can not empty")]
        public System.DateTime ngayNhan { get; set; }


        [Display(Name = "Ngày trả")]
        [Required(ErrorMessage = "Can not empty")]
        public System.DateTime ngayTra { get; set; }


        [Display(Name = "Ngày đặt xe")]
        [Required(ErrorMessage = "Can not empty")]
        public System.DateTime ngayDatXe { get; set; }


        [Display(Name = "Ngày hẹn lấy")]
        [Required(ErrorMessage = "Can not empty")]
        public System.DateTime ngayHenLay { get; set; }


        [Display(Name = "Tiền thuê")]
        [Required(ErrorMessage = "Can not empty")]
        public int tienThue { get; set; }

        public virtual HopDong HopDong { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Xe Xe { get; set; }
    }
}